version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/usr/src/proto:cached
    ports:
      - "${WEB_LOCAL_PORT}:80"
    depends_on:
      - db

  sqladmin:
    image: dpage/pgadmin4
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    ports:
      - "${PGADMIN_LOCAL_PORT}:80"
